### ISSUE TITLE
How to theme with new Material theming method

### ISSUE THREAD

**Issue by tutkli** [dhutaryan/ngx-mat-timepicker#199]
Hi, In Angular Material 19 they introduced a new `mat.theme` mixin to define the themes.

https://material.angular.io/guide/theming#getting-started

The docs here still use the old way of theming. How can we adapt it to the new mixin?

**Comment by dhutaryan** [comment]
Timepicker doesn't have its own theme system and uses the same approach as other material components. Could you tell me what are you gonna do and how? `mat.theme` is used to define the whole theme for all components.

**Comment by tutkli** [comment]
With the new `mat.theme` mixin we no longer have to create the theme in a variable to later use it in their mixin. You create the theme directly, like so: 

```scss
@use '@angular/material' as mat;

html {
  @include mat.theme(
    (
      color: mat.$azure-palette,
      typography: Roboto,
      density: 0,
    )
  );
}
```

Because of that, we no longer have a theme variable to pass to the `mat-timepicker.theme` mixin like the [docs](https://dhutaryan.github.io/ngx-mat-timepicker/#/theming) suggest, and the Timepicker is only partly themed.

I created this [stackblitz](https://stackblitz.com/edit/stackblitz-starters-ahzdd7wy?file=src%2Fmain.ts) for you to see.
